feat(shared/git/hooks/default): add ability to skip hooks by listing in .no-hooks file

diff --git a/shared/git/hooks/default b/shared/git/hooks/default
--- a/shared/git/hooks/default
+++ b/shared/git/hooks/default
@@ -31,7 +31,7 @@ trim() {
 list_include() {
     IFS=',' read -ra arr <<< "$1"
     for i in "${arr[@]}"; do
-        if [[ "$(trim "$i")" == "$(trim "$2")" ]]; then
+        if [[ "$(trim "$i")" == "$(trim "$2")"  || "$(trim "$i")" == "*" ]]; then
             return
         fi
     done
@@ -42,29 +42,37 @@ ARGS=("$@")
 STDIN=$(cat)
 
 maybe_execute() {
+    if [ -e ".no-hooks" ]; then
+        LIST="$(cat .no-hooks)"
+        if [ -z "$LIST" ]; then
+            return
+        else
+            SKIP="$SKIP,$LIST"
+        fi
+    fi
     local HOOK=$1
     if [ "$(echo "$GIT_TRACE_GLOBAL_HOOK" | tr '[:upper:]' '[:lower:]')" == "true" ]; then
         hint "$HOOK ${ARGS[*]}"
     fi
 
     if [ -d "$HOOK" ]; then
-      FAILURE=0
-      for child in "$HOOK"/* ; do
-        echo -n "$STDIN" | maybe_execute "$child" || FAILURE=1
-      done
-      exit $FAILURE
+        FAILURE=0
+        for child in "$HOOK"/* ; do
+            echo -n "$STDIN" | maybe_execute "$child" || FAILURE=1
+        done
+        exit $FAILURE
     elif [ -f "$HOOK" ]; then
         if [ -x "$HOOK" ]; then
-          HOOK_NAME="$(basename "$HOOK")"
-          if list_include "$SKIP" "$HOOK_NAME"; then
-            hint "'$HOOK' skipped."
-          else
-            exec-message "$HOOK"
-            "$HOOK" "${ARGS[@]}" || ( 
-                error-message "$HOOK failed with exit-code $?"; 
-                hint "use SKIP='$HOOK_NAME' to skip this hook."; 
-                exit 1 )
-          fi
+            HOOK_NAME="$(basename "$HOOK")"
+            if list_include "$SKIP" "$HOOK_NAME"; then
+                hint "'$HOOK' skipped."
+            else
+                exec-message "$HOOK"
+                "$HOOK" "${ARGS[@]}" || (
+                    error-message "$HOOK failed with exit-code $?";
+                    hint "use SKIP='$HOOK_NAME' to skip this hook.";
+                    exit 1 )
+            fi
         else
             if [ 'false' != "$(git config --default true --get advice.ignoredHook |\
                 tr '[:upper:]' '[:lower:]')" ]; then
